[package]
name = "chip8-rs"
authors = ["Mickael Lima"]
version = "0.1.0"
edition = "2021"
description = "A simple CHIP-8 interpreter"
license = "GPL-2.0-or-later"

[dependencies]
sdl2 = "0.34.3"
rand = "0.3.14"

